name: Java CD with Maven

on:
  push:
    branches: 
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
#         distribution: 'adopt'
#         cache: maven
        
#     - name: Cache the Maven packages to speed up build
#       uses: actions/cache@v1
#       with:
#         path: ~/.m2
#         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#         restore-keys: ${{ runner.os }}-m2 
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - run: mvn -B package --file pom.xml -DskipTests
    - run: mkdir staging && cp target/*skor-backend.jar staging
    - uses: actions/upload-artifact@v1
      with:
          name: Package
          path: staging
    - 
      name: Login to Gitgub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: build docker images
      run: | 
          docker build . --tag ghcr.io/int222-26-42-45/backend
          docker images
    - name: push docker images to registry
      run: |
          docker push ghcr.io/int222-26-42-45/backend
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.IP }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: |
              export CR_PAT=${{ secrets.GITHUB_TOKEN }} 
              echo $CR_PAT | sudo docker login ghcr.io -u jeongchedah --password-stdin
              sudo docker pull ghcr.io/int222-26-42-45/backend
              sudo docker images
              sudo docker rm backend
              sudo docker run -d --name backend --network skorshopnetwork --ip 172.18.0.3 ghcr.io/int222-26-42-45/backend
